- name: Make sure the mount points of the buckets are present
  file:
    path: "{{ item.value.mountpoint }}"
    state: directory
  loop: "{{ s3fs.buckets | dict2items }}"

- name: Make sure the access keys of buckets are present
  template:
    src: s3fs-passwd.j2
    dest: "{{ s3fs.passwd_file }}"
    mode: 0600
    owner: "{{ ansible_user_id }}"
  notify: restart s3fs

- name: Make sure mountpoints are present in fstab
  mount:
    name: "{{ item.value.mountpoint }}"
    src: "s3fs#{{ key }}:{{ item.value.prefix | default('/') }}"
    fstype: fuse
    opts: "_netdev,{{ item.value.options }},passwd_file={{ s3fs.passwd_file }}"
    state: mounted
  loop: "{{ s3fs.buckets | dict2items }}"
  when: s3fs.buckets is defined
